### ISSUE TITLE
Config Overhaul

### ISSUE THREAD

**Issue by Verticaleap** [findelabs/proxima#19]
Currently Proxima only supports loading a config file for endpoints. This should be changed so that other global params can be specified. One option is below:

```yaml
global:
  network:
    timeout: u32 # 30000
    nodelay: bool # false
    reuse_address: bool # false
    enforce_http: bool # false
  security:
    tls:
      accept_invalid_hostnames: bool # false
      insecure: bool # false
      import_cert: String 
    config:
      hide_folders: bool # false
  integrations:
    vault:
      url: String
      kubernetes_role: String
      mount: String
      login_path: String # auth/kubernetes
      jwt_path: String # /var/run/secrets/kubernetes.io/serviceaccount/token

routes:
  endpoint_locked:
    url: http://myurl.net
    timeout: 5000
    security:
      whitelist:
        methods:
        - GET
        - POST
      client:
        basic:
        - username: client_one
          password: mypasswordone
          whitelist:
            methods:
            - GET
        - username: client_two
          password: mypasswordtwo
```
