### ISSUE TITLE
ConfigMap update for explicit types

### ISSUE THREAD

**Issue by Verticaleap** [findelabs/proxima#36]
We should not assume types, instead we should set endpoint types explicitly:
```yaml
routes:
  endpoint:
    proxy:
      url:
  endpoint:
    vault:
      secret:
  endpoint: 
    http_config:
      url:
```
