### ISSUE TITLE
Proxy setting to retain original Host header

### ISSUE THREAD

**Issue by Verticaleap** [findelabs/proxima#55]
Nginx/Apache have options to retain the original host header for proxy requests. We should add something similar, like:

```yaml
routes:
  route:
    proxy:
      url: http://localhost
      preserve_host: true
```
